const flightList = [
    {
        FlightNumber: 'JET123',
        AirLineName: 'Jet airways',
        Departure: '7:00 Am',
        Arrival: '12:00 Pm',
        Duration: '5 hrs',
        Stops: '2',
        Price: '1500 INR',
        TravelDate: '20-07-2021',
        ReturnDate: '20-07-2021',
        Source: 'Chennai',
        Desitination: 'Mumbai'
    },
    {
        FlightNumber: 'JET233',
        AirLineName: 'Jet airways',
        Departure: '9:00 Am',
        Arrival: '1:00 Pm',
        Duration: '5 hrs',
        Stops: '2',
        Price: '1200 INR',
        TravelDate: '20-07-2021',
        ReturnDate: '20-07-2021',
        Source: 'Chennai',
        Desitination: 'Banglore'
    },
    {
        FlightNumber: 'JET333',
        AirLineName: 'Jet airways',
        Departure: '2:00 Pm',
        Arrival: '4:00 Pm',
        Duration: '2 hrs',
        Stops: '1',
        Price: '1600 INR',
        TravelDate: '20-07-2021',
        ReturnDate: '20-07-2021',
        Source: 'Chennai',
        Desitination: 'Banglore'
    },
    {
        FlightNumber: 'EMR331',
        AirLineName: 'Emirates',
        Departure: '2:00 Pm',
        Arrival: '4:00 Pm',
        Duration: '2 hrs',
        Stops: '1',
        Price: '1300 INR',
        TravelDate: '20-07-2021',
        ReturnDate: '20-07-2021',
        Source: 'Chennai',
        Desitination: 'Banglore'
    },
    {
        FlightNumber: 'EMP331',
        AirLineName: 'Emirates',
        Departure: '2:00 Pm',
        Arrival: '4:00 Pm',
        Duration: '2 hrs',
        Stops: '1',
        Price: '1300 INR',
        TravelDate: '21-07-2021',
        ReturnDate: '21-07-2021',
        Source: 'Chennai',
        Desitination: 'Banglore'
    },
    {
        FlightNumber: 'JET331',
        AirLineName: 'Jet Airways',
        Departure: '12:00 Pm',
        Arrival: '4:00 Pm',
        Duration: '4 hrs',
        Stops: '1',
        Price: '800 INR',
        TravelDate: '21-07-2021',
        ReturnDate: '21-07-2021',
        Source: 'Chennai',
        Desitination: 'Banglore'
    },
    {
        FlightNumber: 'JET338',
        AirLineName: 'Jet Airways',
        Departure: '12:00 Pm',
        Arrival: '4:00 Pm',
        Duration: '4 hrs',
        Stops: '1',
        Price: '800 INR',
        TravelDate: '21-07-2021',
        ReturnDate: '21-07-2021',
        Source: 'Banglore',
        Desitination: 'Chennai'
    },
    {
        FlightNumber: 'SPJ222',
        AirLineName: 'SpiceJet',
        Departure: '08:00 Am',
        Arrival: '11:00 Am',
        Duration: '3 hrs',
        Stops: '1',
        Price: '1000 INR',
        TravelDate: '21-07-2021',
        ReturnDate: '21-07-2021',
        Source: 'Banglore',
        Desitination: 'Chennai'
    },
    {
        FlightNumber: 'SPJ822',
        AirLineName: 'SpiceJet',
        Departure: '10:00 Am',
        Arrival: '01:00 Pm',
        Duration: '3 hrs',
        Stops: '1',
        Price: '900 INR',
        TravelDate: '21-07-2021',
        ReturnDate: '21-07-2021',
        Source: 'Banglore',
        Desitination: 'Chennai'
    },
    {
        FlightNumber: 'SPJ802',
        AirLineName: 'SpiceJet',
        Departure: '10:00 Am',
        Arrival: '01:00 Pm',
        Duration: '3 hrs',
        Stops: '1',
        Price: '900 INR',
        TravelDate: '21-07-2021',
        ReturnDate: '21-07-2021',
        Source: 'Chennai',
        Desitination: 'Mumbai'
    },
    {
        FlightNumber: 'SPJ800',
        AirLineName: 'SpiceJet',
        Departure: '10:00 Am',
        Arrival: '01:00 Pm',
        Duration: '3 hrs',
        Stops: '1',
        Price: '900 INR',
        TravelDate: '21-07-2021',
        ReturnDate: '21-07-2021',
        Source: 'Chennai',
        Desitination: 'Pune'
    },
    {
        FlightNumber: 'EMR800',
        AirLineName: 'Emirates',
        Departure: '11:00 Am',
        Arrival: '03:00 Pm',
        Duration: '4 hrs',
        Stops: '1',
        Price: '900 INR',
        TravelDate: '21-07-2021',
        ReturnDate: '21-07-2021',
        Source: 'Chennai',
        Desitination: 'Pune'
    },
    {
        FlightNumber: 'SPJ900',
        AirLineName: 'SpiceJet',
        Departure: '10:00 Am',
        Arrival: '01:00 Pm',
        Duration: '3 hrs',
        Stops: '1',
        Price: '900 INR',
        TravelDate: '21-07-2021',
        ReturnDate: '21-07-2021',
        Source: 'Chennai',
        Desitination: 'Banglore'
    },
    {
        FlightNumber: 'GOA900',
        AirLineName: 'GoAir',
        Departure: '11:00 Am',
        Arrival: '01:00 Pm',
        Duration: '4 hrs',
        Stops: '1',
        Price: '900 INR',
        TravelDate: '21-07-2021',
        ReturnDate: '21-07-2021',
        Source: 'Chennai',
        Desitination: 'Banglore'
    },
    {
        FlightNumber: 'IGO650',
        AirLineName: 'IndiGo',
        Departure: '11:00 Am',
        Arrival: '01:00 Pm',
        Duration: '4 hrs',
        Stops: '1',
        Price: '900 INR',
        TravelDate: '21-07-2021',
        ReturnDate: '21-07-2021',
        Source: 'Chennai',
        Desitination: 'Banglore'
    },
];


module.exports = flightList